---
settings:
  name: Compute
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-cn,us-en,ja-jp,ko-kr
sidebar:
  entries:
  - title: 所有 Cloud Manager 文档
    url: https://docs.netapp.com/us-en/cloud-manager-family
  - title: 计算文档
    url: "/index.html"
  - title: 发行说明
    url: "/whats-new.html"
  - title: 入门
    entries:
    - title: 了解计算服务
      url: "/concept-compute.html"
    - title: 连接您的 AWS 帐户
      url: "/task-getting-started-compute.html"
  - title: 分析计算成本
    url: "/task-analyze-costs.html"
  - title: 知识和支持
    entries:
    - title: 注册以获得支持
      url: "/task-support-registration.html"
    - title: 获取帮助
      url: "/task-get-help.html"
  - title: 法律声明
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 入门
    links:
    - title: 了解计算服务
      url: concept-compute.html
    - title: 连接您的 AWS 帐户
      url: task-getting-started-compute.html
  - title: 使用计算服务
    links:
    - title: 分析计算成本
      url: task-analyze-costs.html
  - title: 博客社区
    links:
    - title: NetApp 社区
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: Cloud Central 博客
      url: https://cloud.netapp.com/blog
    - title: 云网络研讨会
      url: https://cloud.netapp.com/events
product-family: {}
